channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.1
  - pylint=2.6.0
  - jupyter=1.0.0
  - numpy=1.19.2
  - pandas=1.1.3
  - matplotlib=3.3.2
  - seaborn=0.11.0
  - papermill=2.2.2
  - tabulate=0.8.7
